# Generated by Django 4.0.5 on 2022-07-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('query', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipc', models.CharField(default=True, max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('item_Json', models.CharField(default='', max_length=5000)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=1000)),
                ('a', models.BooleanField(default='soka')),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('image2', models.ImageField(default='', upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
                ('image4', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='studentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
