# Generated by Django 4.0.5 on 2022-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
        migrations.AddField(
            model_name='product',
            name='rex',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='warrenty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
