# Generated by Django 4.0.5 on 2022-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_a_product_rex_product_warrenty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warrenty',
            field=models.CharField(default='1 Year', max_length=100, null=True),
        ),
    ]
