# Generated by Django 4.0.5 on 2022-07-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=100)),
                ('effect', models.IntegerField(max_length=10)),
            ],
        ),
    ]
