# Generated by Django 4.0.5 on 2022-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='effect',
            field=models.IntegerField(default=10),
        ),
    ]
